// Calculate conjugated forms using a rule set

export const rules: any = {
  "godan": {
    "negative": {
      forms: [
        { "before": "る", "after": "らない" },
        { "before": "つ", "after": "たない" },
        { "before": "う", "after": "わない" },
        { "before": "く", "after": "かない" },
        { "before": "ぐ", "after": "がない" },
        { "before": "す", "after": "さない" },
        { "before": "ぬ", "after": "なない" },
        { "before": "ぶ", "after": "ばない" },
        { "before": "む", "after": "まない" },
      ],
    },
    "polite": {
      forms: [
        { "before": "る", "after": "ります" },
        { "before": "つ", "after": "ちます" },
        { "before": "う", "after": "います" },
        { "before": "く", "after": "きます" },
        { "before": "ぐ", "after": "ぎます" },
        { "before": "す", "after": "します" },
        { "before": "ぬ", "after": "にます" },
        { "before": "ぶ", "after": "びます" },
        { "before": "む", "after": "みます" },
      ],
    },
    "polite negative": {
      forms: [
        { "before": "る", "after": "りません" },
        { "before": "つ", "after": "ちません" },
        { "before": "う", "after": "いません" },
        { "before": "く", "after": "きません" },
        { "before": "ぐ", "after": "ぎません" },
        { "before": "す", "after": "しません" },
        { "before": "ぬ", "after": "にません" },
        { "before": "ぶ", "after": "びません" },
        { "before": "む", "after": "みません" },
      ],
    },
    "past": {
      forms: [
        { "before": "る", "after": "った" },
        { "before": "つ", "after": "った" },
        { "before": "う", "after": "った" },
        { "before": "く", "after": "いた" },
        { "before": "ぐ", "after": "いだ" },
        { "before": "す", "after": "した" },
        { "before": "ぬ", "after": "んだ" },
        { "before": "ぶ", "after": "んだ" },
        { "before": "む", "after": "んだ" },
      ],
      tetakei: true,
    },
    "past negative": {
      forms: [
        { "before": "る", "after": "らなかった" },
        { "before": "つ", "after": "たなかった" },
        { "before": "う", "after": "わなかった" },
        { "before": "く", "after": "かなかった" },
        { "before": "ぐ", "after": "がなかった" },
        { "before": "す", "after": "さなかった" },
        { "before": "ぬ", "after": "ななかった" },
        { "before": "ぶ", "after": "ばなかった" },
        { "before": "む", "after": "まなかった" },
      ],
    },
    "polite past": {
      forms: [
        { "before": "る", "after": "りました" },
        { "before": "つ", "after": "ちました" },
        { "before": "う", "after": "いました" },
        { "before": "く", "after": "きました" },
        { "before": "ぐ", "after": "ぎました" },
        { "before": "す", "after": "しました" },
        { "before": "ぬ", "after": "にました" },
        { "before": "ぶ", "after": "びました" },
        { "before": "む", "after": "みました" },
      ],
    },
    "polite past negative": {
      forms: [
        { "before": "る", "after": "りませんでした" },
        { "before": "つ", "after": "ちませんでした" },
        { "before": "う", "after": "いませんでした" },
        { "before": "く", "after": "きませんでした" },
        { "before": "ぐ", "after": "ぎませんでした" },
        { "before": "す", "after": "しませんでした" },
        { "before": "ぬ", "after": "にませんでした" },
        { "before": "ぶ", "after": "びませんでした" },
        { "before": "む", "after": "みませんでした" },
      ],
    },
    "te-form": {
      forms: [
        { "before": "る", "after": "って" },
        { "before": "つ", "after": "って" },
        { "before": "う", "after": "って" },
        { "before": "く", "after": "いて" },
        { "before": "ぐ", "after": "いで" },
        { "before": "す", "after": "して" },
        { "before": "ぬ", "after": "んで" },
        { "before": "ぶ", "after": "んで" },
        { "before": "む", "after": "んで" },
      ],
      tetakei: true,
    },
    "te-form negative": {
      forms: [
        { "before": "る", "after": "らなくて" }, { "before": "る", "after": "らないで" },
        { "before": "つ", "after": "たなくて" }, { "before": "つ", "after": "たないで" },
        { "before": "う", "after": "わなくて" }, { "before": "う", "after": "わないで" },
        { "before": "く", "after": "かなくて" }, { "before": "く", "after": "かないで" },
        { "before": "ぐ", "after": "がなくて" }, { "before": "ぐ", "after": "がないで" },
        { "before": "す", "after": "さなくて" }, { "before": "す", "after": "さないで" },
        { "before": "ぬ", "after": "ななくて" }, { "before": "ぬ", "after": "なないで" },
        { "before": "ぶ", "after": "ばなくて" }, { "before": "ぶ", "after": "ばないで" },
        { "before": "む", "after": "まなくて" }, { "before": "む", "after": "まないで" },
      ],
    },
    "potential": {
      forms: [
        { "before": "る", "after": "れる" },
        { "before": "つ", "after": "てる" },
        { "before": "う", "after": "える" },
        { "before": "く", "after": "ける" },
        { "before": "ぐ", "after": "げる" },
        { "before": "す", "after": "せる" },
        { "before": "ぬ", "after": "ねる" },
        { "before": "ぶ", "after": "べる" },
        { "before": "む", "after": "める" },
      ],
    },
    "potential negative": {
      forms: [
        { "before": "る", "after": "れない" },
        { "before": "つ", "after": "てない" },
        { "before": "う", "after": "えない" },
        { "before": "く", "after": "けない" },
        { "before": "ぐ", "after": "げない" },
        { "before": "す", "after": "せない" },
        { "before": "ぬ", "after": "ねない" },
        { "before": "ぶ", "after": "べない" },
        { "before": "む", "after": "めない" },
      ],
    },
    "polite potential": {
      forms: [
        { "before": "る", "after": "れます" },
        { "before": "つ", "after": "てます" },
        { "before": "う", "after": "えます" },
        { "before": "く", "after": "けます" },
        { "before": "ぐ", "after": "げます" },
        { "before": "す", "after": "せます" },
        { "before": "ぬ", "after": "ねます" },
        { "before": "ぶ", "after": "べます" },
        { "before": "む", "after": "めます" },
      ],
    },
    "polite potential negative": {
      forms: [
        { "before": "る", "after": "れません" },
        { "before": "つ", "after": "てません" },
        { "before": "う", "after": "えません" },
        { "before": "く", "after": "けません" },
        { "before": "ぐ", "after": "げません" },
        { "before": "す", "after": "せません" },
        { "before": "ぬ", "after": "ねません" },
        { "before": "ぶ", "after": "べません" },
        { "before": "む", "after": "めません" },
      ],
    },
    "passive": {
      forms: [
        { "before": "る", "after": "られる" },
        { "before": "つ", "after": "たれる" },
        { "before": "う", "after": "われる" },
        { "before": "く", "after": "かれる" },
        { "before": "ぐ", "after": "がれる" },
        { "before": "す", "after": "される" },
        { "before": "ぬ", "after": "なれる" },
        { "before": "ぶ", "after": "ばれる" },
        { "before": "む", "after": "まれる" },
      ],
    },
    "passive negative": {
      forms: [
        { "before": "る", "after": "られない" },
        { "before": "つ", "after": "たれない" },
        { "before": "う", "after": "われない" },
        { "before": "く", "after": "かれない" },
        { "before": "ぐ", "after": "がれない" },
        { "before": "す", "after": "されない" },
        { "before": "ぬ", "after": "なれない" },
        { "before": "ぶ", "after": "ばれない" },
        { "before": "む", "after": "まれない" },
      ],
    },
    "passive past": {
      forms: [
        { "before": "る", "after": "られた" },
        { "before": "つ", "after": "たれた" },
        { "before": "う", "after": "われた" },
        { "before": "く", "after": "かれた" },
        { "before": "ぐ", "after": "がれた" },
        { "before": "す", "after": "された" },
        { "before": "ぬ", "after": "なれた" },
        { "before": "ぶ", "after": "ばれた" },
        { "before": "む", "after": "まれた" },
      ],
    },
    "passive past negative": {
      forms: [
        { "before": "る", "after": "られなかった" },
        { "before": "つ", "after": "たれなかった" },
        { "before": "う", "after": "われなかった" },
        { "before": "く", "after": "かれなかった" },
        { "before": "ぐ", "after": "がれなかった" },
        { "before": "す", "after": "されなかった" },
        { "before": "ぬ", "after": "なれなかった" },
        { "before": "ぶ", "after": "ばれなかった" },
        { "before": "む", "after": "まれなかった" },
      ],
    },
    "passive te-form": {
      forms: [
        { "before": "る", "after": "られて" },
        { "before": "つ", "after": "たれて" },
        { "before": "う", "after": "われて" },
        { "before": "く", "after": "かれて" },
        { "before": "ぐ", "after": "がれて" },
        { "before": "す", "after": "されて" },
        { "before": "ぬ", "after": "なれて" },
        { "before": "ぶ", "after": "ばれて" },
        { "before": "む", "after": "まれて" },
      ],
    },
    "polite passive": {
      forms: [
        { "before": "る", "after": "られます" },
        { "before": "つ", "after": "たれます" },
        { "before": "う", "after": "われます" },
        { "before": "く", "after": "かれます" },
        { "before": "ぐ", "after": "がれます" },
        { "before": "す", "after": "されます" },
        { "before": "ぬ", "after": "なれます" },
        { "before": "ぶ", "after": "ばれます" },
        { "before": "む", "after": "まれます" },
      ],
    },
    "polite passive negative": {
      forms: [
        { "before": "る", "after": "られません" },
        { "before": "つ", "after": "たれません" },
        { "before": "う", "after": "われません" },
        { "before": "く", "after": "かれません" },
        { "before": "ぐ", "after": "がれません" },
        { "before": "す", "after": "されません" },
        { "before": "ぬ", "after": "なれません" },
        { "before": "ぶ", "after": "ばれません" },
        { "before": "む", "after": "まれません" },
      ],
    },
    "polite passive past": {
      forms: [
        { "before": "る", "after": "られました" },
        { "before": "つ", "after": "たれました" },
        { "before": "う", "after": "われました" },
        { "before": "く", "after": "かれました" },
        { "before": "ぐ", "after": "がれました" },
        { "before": "す", "after": "されました" },
        { "before": "ぬ", "after": "なれました" },
        { "before": "ぶ", "after": "ばれました" },
        { "before": "む", "after": "まれました" },
      ],
    },
    "polite passive past negative": {
      forms: [
        { "before": "る", "after": "られませんでした" },
        { "before": "つ", "after": "たれませんでした" },
        { "before": "う", "after": "われませんでした" },
        { "before": "く", "after": "かれませんでした" },
        { "before": "ぐ", "after": "がれませんでした" },
        { "before": "す", "after": "されませんでした" },
        { "before": "ぬ", "after": "なれませんでした" },
        { "before": "ぶ", "after": "ばれませんでした" },
        { "before": "む", "after": "まれませんでした" },
      ],
    },
    "causative": {
      forms: [
        { "before": "る", "after": "らせる" },
        { "before": "つ", "after": "たせる" },
        { "before": "う", "after": "わせる" },
        { "before": "く", "after": "かせる" },
        { "before": "ぐ", "after": "がせる" },
        { "before": "す", "after": "させる" },
        { "before": "ぬ", "after": "なせる" },
        { "before": "ぶ", "after": "ばせる" },
        { "before": "む", "after": "ませる" },
      ],
    },
    "causative negative": {
      forms: [
        { "before": "る", "after": "らせない" },
        { "before": "つ", "after": "たせない" },
        { "before": "う", "after": "わせない" },
        { "before": "く", "after": "かせない" },
        { "before": "ぐ", "after": "がせない" },
        { "before": "す", "after": "させない" },
        { "before": "ぬ", "after": "なせない" },
        { "before": "ぶ", "after": "ばせない" },
        { "before": "む", "after": "ませない" },
      ],
    },
    "causative past": {
      forms: [
        { "before": "る", "after": "らせた" },
        { "before": "つ", "after": "たせた" },
        { "before": "う", "after": "わせた" },
        { "before": "く", "after": "かせた" },
        { "before": "ぐ", "after": "がせた" },
        { "before": "す", "after": "させた" },
        { "before": "ぬ", "after": "なせた" },
        { "before": "ぶ", "after": "ばせた" },
        { "before": "む", "after": "ませた" },
      ],
    },
    "causative past negative": {
      forms: [
        { "before": "る", "after": "らせなかった" },
        { "before": "つ", "after": "たせなかった" },
        { "before": "う", "after": "わせなかった" },
        { "before": "く", "after": "かせなかった" },
        { "before": "ぐ", "after": "がせなかった" },
        { "before": "す", "after": "させなかった" },
        { "before": "ぬ", "after": "なせなかった" },
        { "before": "ぶ", "after": "ばせなかった" },
        { "before": "む", "after": "ませなかった" },
      ],
    },
    "causative passive": {
      forms: [
        { "before": "る", "after": "らせられる" },
        { "before": "つ", "after": "たせられる" },
        { "before": "う", "after": "わせられる" },
        { "before": "く", "after": "かせられる" },
        { "before": "ぐ", "after": "がせられる" },
        { "before": "す", "after": "させられる" },
        { "before": "ぬ", "after": "なせられる" },
        { "before": "ぶ", "after": "ばせられる" },
        { "before": "む", "after": "ませられる" },
      ],
    },
    "causative passive negative": {
      forms: [
        { "before": "る", "after": "らせられない" },
        { "before": "つ", "after": "たせられない" },
        { "before": "う", "after": "わせられない" },
        { "before": "く", "after": "かせられない" },
        { "before": "ぐ", "after": "がせられない" },
        { "before": "す", "after": "させられない" },
        { "before": "ぬ", "after": "なせられない" },
        { "before": "ぶ", "after": "ばせられない" },
        { "before": "む", "after": "ませられない" },
      ],
    },
    "causative passive past": {
      forms: [
        { "before": "る", "after": "らせられた" },
        { "before": "つ", "after": "たせられた" },
        { "before": "う", "after": "わせられた" },
        { "before": "く", "after": "かせられた" },
        { "before": "ぐ", "after": "がせられた" },
        { "before": "す", "after": "させられた" },
        { "before": "ぬ", "after": "なせられた" },
        { "before": "ぶ", "after": "ばせられた" },
        { "before": "む", "after": "ませられた" },
      ],
    },
    "causative passive negative past": {
      forms: [
        { "before": "る", "after": "らせられなかった" },
        { "before": "つ", "after": "たせられなかった" },
        { "before": "う", "after": "わせられなかった" },
        { "before": "く", "after": "かせられなかった" },
        { "before": "ぐ", "after": "がせられなかった" },
        { "before": "す", "after": "させられなかった" },
        { "before": "ぬ", "after": "なせられなかった" },
        { "before": "ぶ", "after": "ばせられなかった" },
        { "before": "む", "after": "ませられなかった" },
      ],
    },
    "imperative": {
      forms: [
        { "before": "る", "after": "れ" },
        { "before": "つ", "after": "て" },
        { "before": "う", "after": "え" },
        { "before": "く", "after": "け" },
        { "before": "ぐ", "after": "げ" },
        { "before": "す", "after": "せ" },
        { "before": "ぬ", "after": "ね" },
        { "before": "ぶ", "after": "べ" },
        { "before": "む", "after": "め" },
      ],
    },
    "imperative negative": {
      forms: [
        { "before": "る", "after": "るな" },
        { "before": "つ", "after": "つな" },
        { "before": "う", "after": "うな" },
        { "before": "く", "after": "くな" },
        { "before": "ぐ", "after": "ぐな" },
        { "before": "す", "after": "すな" },
        { "before": "ぬ", "after": "ぬな" },
        { "before": "ぶ", "after": "ぶな" },
        { "before": "む", "after": "むな" },
      ],
    },
    "progressive": {
      forms: [
        { "before": "る", "after": "っている" },
        { "before": "つ", "after": "っている" },
        { "before": "う", "after": "っている" },
        { "before": "く", "after": "いている" },
        { "before": "ぐ", "after": "いでいる" },
        { "before": "す", "after": "している" },
        { "before": "ぬ", "after": "んでいる" },
        { "before": "ぶ", "after": "んでいる" },
        { "before": "む", "after": "んでいる" },
      ],
      tetakei: true,
    },
    "progressive negative": {
      forms: [
        { "before": "る", "after": "っていない" },
        { "before": "つ", "after": "っていない" },
        { "before": "う", "after": "っていない" },
        { "before": "く", "after": "いていない" },
        { "before": "ぐ", "after": "いでいない" },
        { "before": "す", "after": "していない" },
        { "before": "ぬ", "after": "んでいない" },
        { "before": "ぶ", "after": "んでいない" },
        { "before": "む", "after": "んでいない" },
      ],
      tetakei: true,
    },
    "polite progressive": {
      forms: [
        { "before": "る", "after": "っています" },
        { "before": "つ", "after": "っています" },
        { "before": "う", "after": "っています" },
        { "before": "く", "after": "いています" },
        { "before": "ぐ", "after": "いでいます" },
        { "before": "す", "after": "しています" },
        { "before": "ぬ", "after": "んでいます" },
        { "before": "ぶ", "after": "んでいます" },
        { "before": "む", "after": "んでいます" },
      ],
      tetakei: true,
    },
    "polite progressive negative": {
      forms: [
        { "before": "る", "after": "っていません" },
        { "before": "つ", "after": "っていません" },
        { "before": "う", "after": "っていません" },
        { "before": "く", "after": "いていません" },
        { "before": "ぐ", "after": "いでいません" },
        { "before": "す", "after": "していません" },
        { "before": "ぬ", "after": "んでいません" },
        { "before": "ぶ", "after": "んでいません" },
        { "before": "む", "after": "んでいません" },
      ],
      tetakei: true,
    },
    "progressive past": {
      forms: [
        { "before": "る", "after": "っていた" },
        { "before": "つ", "after": "っていた" },
        { "before": "う", "after": "っていた" },
        { "before": "く", "after": "いていた" },
        { "before": "ぐ", "after": "いでいた" },
        { "before": "す", "after": "していた" },
        { "before": "ぬ", "after": "んでいた" },
        { "before": "ぶ", "after": "んでいた" },
        { "before": "む", "after": "んでいた" },
      ],
      tetakei: true,
    },
    "progressive past negative": {
      forms: [
        { "before": "る", "after": "っていなかった" },
        { "before": "つ", "after": "っていなかった" },
        { "before": "う", "after": "っていなかった" },
        { "before": "く", "after": "いていなかった" },
        { "before": "ぐ", "after": "いでいなかった" },
        { "before": "す", "after": "していなかった" },
        { "before": "ぬ", "after": "んでいなかった" },
        { "before": "ぶ", "after": "んでいなかった" },
        { "before": "む", "after": "んでいなかった" },
      ],
      tetakei: true,
    },
    "polite progressive past": {
      forms: [
        { "before": "る", "after": "っていました" },
        { "before": "つ", "after": "っていました" },
        { "before": "う", "after": "っていました" },
        { "before": "く", "after": "いていました" },
        { "before": "ぐ", "after": "いでいました" },
        { "before": "す", "after": "していました" },
        { "before": "ぬ", "after": "んでいました" },
        { "before": "ぶ", "after": "んでいました" },
        { "before": "む", "after": "んでいました" },
      ],
      tetakei: true,
    },
    "polite progressive past negative": {
      forms: [
        { "before": "る", "after": "っていませんでした" },
        { "before": "つ", "after": "っていませんでした" },
        { "before": "う", "after": "っていませんでした" },
        { "before": "く", "after": "いていませんでした" },
        { "before": "ぐ", "after": "いでいませんでした" },
        { "before": "す", "after": "していませんでした" },
        { "before": "ぬ", "after": "んでいませんでした" },
        { "before": "ぶ", "after": "んでいませんでした" },
        { "before": "む", "after": "んでいませんでした" },
      ],
      tetakei: true,
    },
    "desire": {
      forms: [
        { "before": "る", "after": "りたい" },
        { "before": "つ", "after": "ちたい" },
        { "before": "う", "after": "いたい" },
        { "before": "く", "after": "きたい" },
        { "before": "ぐ", "after": "ぎたい" },
        { "before": "す", "after": "したい" },
        { "before": "ぬ", "after": "にたい" },
        { "before": "ぶ", "after": "びたい" },
        { "before": "む", "after": "みたい" },
      ],
    },
    "desire negative": {
      forms: [
        { "before": "る", "after": "りたくない" },
        { "before": "つ", "after": "ちたくない" },
        { "before": "う", "after": "いたくない" },
        { "before": "く", "after": "きたくない" },
        { "before": "ぐ", "after": "ぎたくない" },
        { "before": "す", "after": "したくない" },
        { "before": "ぬ", "after": "にたくない" },
        { "before": "ぶ", "after": "びたくない" },
        { "before": "む", "after": "みたくない" },
      ],
    },
    "desire past": {
      forms: [
        { "before": "る", "after": "りたかった" },
        { "before": "つ", "after": "ちたかった" },
        { "before": "う", "after": "いたかった" },
        { "before": "く", "after": "きたかった" },
        { "before": "ぐ", "after": "ぎたかった" },
        { "before": "す", "after": "したかった" },
        { "before": "ぬ", "after": "にたかった" },
        { "before": "ぶ", "after": "びたかった" },
        { "before": "む", "after": "みたかった" },
      ],
    },
    "desire past negative": {
      forms: [
        { "before": "る", "after": "りたくなかった" },
        { "before": "つ", "after": "ちたくなかった" },
        { "before": "う", "after": "いたくなかった" },
        { "before": "く", "after": "きたくなかった" },
        { "before": "ぐ", "after": "ぎたくなかった" },
        { "before": "す", "after": "したくなかった" },
        { "before": "ぬ", "after": "にたくなかった" },
        { "before": "ぶ", "after": "びたくなかった" },
        { "before": "む", "after": "みたくなかった" },
      ],
    },
    "desire te-form": {
      forms: [
        { "before": "る", "after": "りたくて" },
        { "before": "つ", "after": "ちたくて" },
        { "before": "う", "after": "いたくて" },
        { "before": "く", "after": "きたくて" },
        { "before": "ぐ", "after": "ぎたくて" },
        { "before": "す", "after": "したくて" },
        { "before": "ぬ", "after": "にたくて" },
        { "before": "ぶ", "after": "びたくて" },
        { "before": "む", "after": "みたくて" },
      ],
    },
    "desire te-form negative": {
      forms: [
        { "before": "る", "after": "りたくなくて" },
        { "before": "つ", "after": "ちたくなくて" },
        { "before": "う", "after": "いたくなくて" },
        { "before": "く", "after": "きたくなくて" },
        { "before": "ぐ", "after": "ぎたくなくて" },
        { "before": "す", "after": "したくなくて" },
        { "before": "ぬ", "after": "にたくなくて" },
        { "before": "ぶ", "after": "びたくなくて" },
        { "before": "む", "after": "みたくなくて" },
      ],
    },
    "desire polite": {
      forms: [
        { "before": "る", "after": "りたいです" },
        { "before": "つ", "after": "ちたいです" },
        { "before": "う", "after": "いたいです" },
        { "before": "く", "after": "きたいです" },
        { "before": "ぐ", "after": "ぎたいです" },
        { "before": "す", "after": "したいです" },
        { "before": "ぬ", "after": "にたいです" },
        { "before": "ぶ", "after": "びたいです" },
        { "before": "む", "after": "みたいです" },
      ],
    },
    "desire polite negative": {
      forms: [
        { "before": "る", "after": "りたくないです" },
        { "before": "つ", "after": "ちたくないです" },
        { "before": "う", "after": "いたくないです" },
        { "before": "く", "after": "きたくないです" },
        { "before": "ぐ", "after": "ぎたくないです" },
        { "before": "す", "after": "したくないです" },
        { "before": "ぬ", "after": "にたくないです" },
        { "before": "ぶ", "after": "びたくないです" },
        { "before": "む", "after": "みたくないです" },
      ],
    },
    "desire polite past": {
      forms: [
        { "before": "る", "after": "りたかったです" },
        { "before": "つ", "after": "ちたかったです" },
        { "before": "う", "after": "いたかったです" },
        { "before": "く", "after": "きたかったです" },
        { "before": "ぐ", "after": "ぎたかったです" },
        { "before": "す", "after": "したかったです" },
        { "before": "ぬ", "after": "にたかったです" },
        { "before": "ぶ", "after": "びたかったです" },
        { "before": "む", "after": "みたかったです" },
      ],
    },
    "desire polite past negative": {
      forms: [
        { "before": "る", "after": "りたくなかったです" },
        { "before": "つ", "after": "ちたくなかったです" },
        { "before": "う", "after": "いたくなかったです" },
        { "before": "く", "after": "きたくなかったです" },
        { "before": "ぐ", "after": "ぎたくなかったです" },
        { "before": "す", "after": "したくなかったです" },
        { "before": "ぬ", "after": "にたくなかったです" },
        { "before": "ぶ", "after": "びたくなかったです" },
        { "before": "む", "after": "みたくなかったです" },
      ],
    },
    "volitional": {
      forms: [
        { "before": "る", "after": "ろう" },
        { "before": "つ", "after": "とう" },
        { "before": "う", "after": "おう" },
        { "before": "く", "after": "こう" },
        { "before": "ぐ", "after": "ごう" },
        { "before": "す", "after": "そう" },
        { "before": "ぬ", "after": "のう" },
        { "before": "ぶ", "after": "ぼう" },
        { "before": "む", "after": "もう" },
      ],
    },
    "polite volitional": {
      forms: [
        { "before": "る", "after": "りましょう" },
        { "before": "つ", "after": "ちましょう" },
        { "before": "う", "after": "いましょう" },
        { "before": "く", "after": "きましょう" },
        { "before": "ぐ", "after": "ぎましょう" },
        { "before": "す", "after": "しましょう" },
        { "before": "ぬ", "after": "にましょう" },
        { "before": "ぶ", "after": "びましょう" },
        { "before": "む", "after": "みましょう" },
      ],
    },
  },

  "ichidan": {
    "negative": { forms: [ { "before": "る", "after": "ない" } ] },
    "polite": { forms: [ { "before": "る", "after": "ます" } ] },
    "polite negative": { forms: [ { "before": "る", "after": "ません" } ] },
    "past": { forms: [ { "before": "る", "after": "た" } ] },
    "past negative": { forms: [ { "before": "る", "after": "なかった" } ] },
    "polite past": { forms: [ { "before": "る", "after": "ました" } ] },
    "polite past negative": { forms: [ { "before": "る", "after": "ませんでした" } ] },
    "te-form": { forms: [ { "before": "る", "after": "て" } ] },
    "te-form negative": { forms: [ { "before": "る", "after": "なくて" }, { "before": "る", "after": "ないで" } ] },
    "potential": { forms: [ { "before": "る", "after": "られる" }, { "before": "る", "after": "れる" } ] },
    "potential negative": { forms: [ { "before": "る", "after": "られない" } ] },
    "polite potential": { forms: [ { "before": "る", "after": "られます" } ] },
    "polite potential negative": { forms: [ { "before": "る", "after": "られません" } ] },
    "imperative": { forms: [ { "before": "る", "after": "ろ" } ] },
    "imperative negative": { forms: [ { "before": "る", "after": "るな" } ] },
    "passive": { forms: [ { "before": "る", "after": "られる" } ] },
    "passive negative": { forms: [ { "before": "る", "after": "られない" } ] },
    "passive past": { forms: [ { "before": "る", "after": "られた" } ] },
    "passive past negative": { forms: [ { "before": "る", "after": "られなかった" } ] },
    "passive te-form": { forms: [ { "before": "る", "after": "られて" } ] },
    "polite passive": { forms: [ { "before": "る", "after": "られます" } ] },
    "polite passive negative": { forms: [ { "before": "る", "after": "られません" } ] },
    "polite passive past": { forms: [ { "before": "る", "after": "られました" } ] },
    "polite passive past negative": { forms: [ { "before": "る", "after": "られませんでした" } ] },
    "causative": { forms: [ { "before": "る", "after": "させる" } ] },
    "causative negative": { forms: [ { "before": "る", "after": "させない" } ] },
    "causative past": { forms: [ { "before": "る", "after": "させた" } ] },
    "causative past negative": { forms: [ { "before": "る", "after": "させなかった" } ] },
    "causative passive": { forms: [ { "before": "る", "after": "させられる" } ] },
    "causative passive negative": { forms: [ { "before": "る", "after": "させられない" } ] },
    "causative passive past": { forms: [ { "before": "る", "after": "させられた" } ] },
    "causative passive past negative": { forms: [ { "before": "る", "after": "させられなかった" } ] },
    "progressive": { forms: [ { "before": "る", "after": "ている" } ] },
    "progressive negative": { forms: [ { "before": "る", "after": "ていない" } ] },
    "polite progressive": { forms: [ { "before": "る", "after": "ています" } ] },
    "polite progressive negative": { forms: [ { "before": "る", "after": "ていません" } ] },
    "progressive past": { forms: [ { "before": "る", "after": "ていた" } ] },
    "progressive past negative": { forms: [ { "before": "る", "after": "ていなかった" } ] },
    "polite progressive past": { forms: [ { "before": "る", "after": "ていました" } ] },
    "polite progressive past negative": { forms: [ { "before": "る", "after": "ていませんでした" } ] },
    "desire": { forms: [ { "before": "る", "after": "たい" } ] },
    "desire negative": { forms: [ { "before": "る", "after": "たくない" } ] },
    "desire past": { forms: [ { "before": "る", "after": "たかった" } ] },
    "desire past negative": { forms: [ { "before": "る", "after": "たくなかった" } ] },
    "desire te-form": { forms: [ { "before": "る", "after": "たくて" } ] },
    "desire te-form negative": { forms: [ { "before": "る", "after": "たくなくて" } ] },
    "desire polite": { forms: [ { "before": "る", "after": "たいです" } ] },
    "desire polite negative": { forms: [ { "before": "る", "after": "たくないです" } ] },
    "desire polite past": { forms: [ { "before": "る", "after": "たかったです" } ] },
    "desire polite past negative": { forms: [ { "before": "る", "after": "たくなかったです" } ] },
    "volitional": { forms: [ { "before": "る", "after": "よう" } ] },
    "polite volitional": { forms: [ { "before": "る", "after": "ましょう" } ] },
  },

  "iku": {
    "negative": { forms: [ { "before": "く", "after": "かない" } ] },
    "polite": { forms: [ { "before": "く", "after": "きます" } ] },
    "polite negative": { forms: [ { "before": "く", "after": "きません" } ] },
    "past": { forms: [ { "before": "く", "after": "った" } ] },
    "past negative": { forms: [ { "before": "く", "after": "かなかった" } ] },
    "polite past": { forms: [ { "before": "く", "after": "きました" } ] },
    "polite past negative": { forms: [ { "before": "く", "after": "きませんでした" } ] },
    "te-form": { forms: [ { "before": "く", "after": "って" } ] },
    "te-form negative": { forms: [ { "before": "く", "after": "かなくて" }, { "before": "く", "after": "かないで" } ] },
    "potential": { forms: [ { "before": "く", "after": "ける" } ] },
    "potential negative": { forms: [ { "before": "く", "after": "けない" } ] },
    "polite potential": { forms: [ { "before": "く", "after": "けます" } ] },
    "polite potential negative": { forms: [ { "before": "く", "after": "けません" } ] },
    "imperative": { forms: [ { "before": "く", "after": "け" } ] },
    "imperative negative": { forms: [ { "before": "く", "after": "くな" } ] },
    "passive": { forms: [ { "before": "く", "after": "かれる" } ] },
    "passive negative": { forms: [ { "before": "く", "after": "かれない" } ] },
    "passive past": { forms: [ { "before": "く", "after": "かれた" } ] },
    "passive past negative": { forms: [ { "before": "く", "after": "かれなかった" } ] },
    "passive te-form": { forms: [ { "before": "く", "after": "かれて" } ] },
    "polite passive": { forms: [ { "before": "く", "after": "かれます" } ] },
    "polite passive negative": { forms: [ { "before": "く", "after": "かれません" } ] },
    "polite passive past": { forms: [ { "before": "く", "after": "かれました" } ] },
    "polite passive past negative": { forms: [ { "before": "く", "after": "かれませんでした" } ] },
    "causative": { forms: [ { "before": "く", "after": "かせる" } ] },
    "causative negative": { forms: [ { "before": "く", "after": "かせない" } ] },
    "causative past": { forms: [ { "before": "く", "after": "かせた" } ] },
    "causative past negative": { forms: [ { "before": "く", "after": "かせなかった" } ] },
    "causative passive": { forms: [ { "before": "く", "after": "かせられる" } ] },
    "causative passive negative": { forms: [ { "before": "く", "after": "かせられない" } ] },
    "causative passive past": { forms: [ { "before": "く", "after": "かせられた" } ] },
    "causative passive past negative": { forms: [ { "before": "く", "after": "かせられなかった" } ] },
    "progressive": { forms: [ { "before": "く", "after": "いている" } ] },
    "progressive negative": { forms: [ { "before": "く", "after": "いていない" } ] },
    "polite progressive": { forms: [ { "before": "く", "after": "いています" } ] },
    "polite progressive negative": { forms: [ { "before": "く", "after": "いていません" } ] },
    "progressive past": { forms: [ { "before": "く", "after": "いていた" } ] },
    "progressive past negative": { forms: [ { "before": "く", "after": "いていなかった" } ] },
    "polite progressive past": { forms: [ { "before": "く", "after": "いていました" } ] },
    "polite progressive past negative": { forms: [ { "before": "く", "after": "いていませんでした" } ] },
    "desire": { forms: [ { "before": "く", "after": "きたい" } ] },
    "desire negative": { forms: [ { "before": "く", "after": "きたくない" } ] },
    "desire past": { forms: [ { "before": "く", "after": "きたかった" } ] },
    "desire past negative": { forms: [ { "before": "く", "after": "きたくなかった" } ] },
    "desire te-form": { forms: [ { "before": "く", "after": "きたくて" } ] },
    "desire te-form negative": { forms: [ { "before": "く", "after": "きたくなくて" } ] },
    "desire polite": { forms: [ { "before": "く", "after": "きたいです" } ] },
    "desire polite negative": { forms: [ { "before": "く", "after": "きたくないです" } ] },
    "desire polite past": { forms: [ { "before": "く", "after": "きたかったです" } ] },
    "desire polite past negative": { forms: [ { "before": "く", "after": "きたくなかったです" } ] },
    "volitional": { forms: [ { "before": "く", "after": "こう" } ] },
    "polite volitional": { forms: [ { "before": "く", "after": "きましょう" } ] },
  },

  "kuru": {
    "negative": { forms: [ { "before": "来る", "after": "来ない" }, { "before": "くる", "after": "こない" } ] },
    "polite": { forms: [ { "before": "来る", "after": "来ます" }, { "before": "くる", "after": "きます" } ] },
    "polite negative": { forms: [ { "before": "来る", "after": "来ません" }, { "before": "くる", "after": "きません" } ] },
    "past": { forms: [ { "before": "来る", "after": "来た" }, { "before": "くる", "after": "きた" } ] },
    "past negative": { forms: [ { "before": "来る", "after": "来なかった" }, { "before": "くる", "after": "こなかった" } ] },
    "polite past": { forms: [ { "before": "来る", "after": "来ました" }, { "before": "くる", "after": "きました" } ] },
    "polite past negative": { forms: [ { "before": "来る", "after": "来ませんでした" }, { "before": "くる", "after": "きませんでした" } ] },
    "te-form": { forms: [ { "before": "来る", "after": "来て" }, { "before": "くる", "after": "きて" } ] },
    "te-form negative": { forms: [ { "before": "来る", "after": "来なくて" }, { "before": "くる", "after": "こなくて" }, { "before": "来る", "after": "来ないで" }, { "before": "くる", "after": "こないで" } ] },
    "potential": { forms: [ { "before": "来る", "after": "来られる" }, { "before": "くる", "after": "こられる" } ] },
    "potential negative": { forms: [ { "before": "来る", "after": "来られない" }, { "before": "くる", "after": "こられない" } ] },
    "polite potential": { forms: [ { "before": "来る", "after": "来られます" }, { "before": "くる", "after": "こられます" } ] },
    "polite potential negative": { forms: [ { "before": "来る", "after": "来られません" }, { "before": "くる", "after": "こられません" } ] },
    "imperative": { forms: [ { "before": "来る", "after": "来い" }, { "before": "くる", "after": "こい" } ] },
    "imperative negative": { forms: [ { "before": "来る", "after": "来るな" }, { "before": "くる", "after": "くるな" } ] },
    "passive": { forms: [ { "before": "来る", "after": "来られる" }, { "before": "くる", "after": "こられる" } ] },
    "passive negative": { forms: [ { "before": "来る", "after": "来られない" }, { "before": "くる", "after": "こられない" } ] },
    "passive past": { forms: [ { "before": "来る", "after": "来られた" }, { "before": "くる", "after": "こられた" } ] },
    "passive past negative": { forms: [ { "before": "来る", "after": "来られなかった" }, { "before": "くる", "after": "こられなかった" } ] },
    "passive te-form": { forms: [ { "before": "来る", "after": "来られて" }, { "before": "くる", "after": "こられて" } ] },
    "polite passive": { forms: [ { "before": "来る", "after": "来られます" }, { "before": "くる", "after": "こられます" } ] },
    "polite passive negative": { forms: [ { "before": "来る", "after": "来られません" }, { "before": "くる", "after": "こられません" } ] },
    "polite passive past": { forms: [ { "before": "来る", "after": "来られました" }, { "before": "くる", "after": "こられました" } ] },
    "polite passive past negative": { forms: [ { "before": "来る", "after": "来られませんでした" }, { "before": "くる", "after": "こられませんでした" } ] },
    "causative": { forms: [ { "before": "来る", "after": "来させる" }, { "before": "くる", "after": "こさせる" } ] },
    "causative negative": { forms: [ { "before": "来る", "after": "来させない" }, { "before": "くる", "after": "こさせない" } ] },
    "causative past": { forms: [ { "before": "来る", "after": "来させた" }, { "before": "くる", "after": "こさせた" } ] },
    "causative past negative": { forms: [ { "before": "来る", "after": "来させなかった" }, { "before": "くる", "after": "こさせなかった" } ] },
    "causative passive": { forms: [ { "before": "来る", "after": "来させられる" }, { "before": "くる", "after": "こさせられる" } ] },
    "causative passive negative": { forms: [ { "before": "来る", "after": "来させられない" }, { "before": "くる", "after": "こさせられない" } ] },
    "causative passive past": { forms: [ { "before": "来る", "after": "来させられた" }, { "before": "くる", "after": "こさせられた" } ] },
    "causative passive past negative": { forms: [ { "before": "来る", "after": "来させられなかった" }, { "before": "くる", "after": "こさせられなかった" } ] },
    "progressive": { forms: [ { "before": "来る", "after": "来ている" }, { "before": "くる", "after": "きている" } ] },
    "progressive negative": { forms: [ { "before": "来る", "after": "来ている" }, { "before": "くる", "after": "きていない" } ] },
    "polite progressive": { forms: [ { "before": "来る", "after": "来ています" }, { "before": "くる", "after": "きています" } ] },
    "polite progressive negative": { forms: [ { "before": "来る", "after": "来ていません" }, { "before": "くる", "after": "きていません" } ] },
    "progressive past": { forms: [ { "before": "来る", "after": "来ていた" }, { "before": "くる", "after": "きていた" } ] },
    "progressive past negative": { forms: [ { "before": "来る", "after": "来ていなかった" }, { "before": "くる", "after": "きていなかった" } ] },
    "polite progressive past": { forms: [ { "before": "来る", "after": "来ていました" }, { "before": "くる", "after": "きていました" } ] },
    "polite progressive past negative": { forms: [ { "before": "来る", "after": "来ていませんでした" }, { "before": "くる", "after": "きていませんでした" } ] },
    "desire": { forms: [ { "before": "来る", "after": "来たい" }, { "before": "くる", "after": "きたい" } ] },
    "desire negative": { forms: [ { "before": "来る", "after": "来たくない" }, { "before": "くる", "after": "きたくない" } ] },
    "desire polite": { forms: [ { "before": "来る", "after": "来たいです" }, { "before": "くる", "after": "きたいです" } ] },
    "desire polite negative": { forms: [ { "before": "来る", "after": "来たくないです" }, { "before": "くる", "after": "きたくないです" } ] },
    "volitional": { forms: [ { "before": "来る", "after": "来よう" }, { "before": "くる", "after": "こよう" } ] },
    "polite volitional": { forms: [ { "before": "来る", "after": "来ましょう" }, { "before": "くる", "after": "きましょう" } ] },
  },

  "suru": {
    "negative": { forms: [ { "before": "する", "after": "しない" } ] },
    "polite": { forms: [ { "before": "する", "after": "します" } ] },
    "polite negative": { forms: [ { "before": "する", "after": "しません" } ] },
    "past": { forms: [ { "before": "する", "after": "した" } ] },
    "past negative": { forms: [ { "before": "する", "after": "しなかった" } ] },
    "polite past": { forms: [ { "before": "する", "after": "しました" } ] },
    "polite past negative": { forms: [ { "before": "する", "after": "しませんでした" } ] },
    "te-form": { forms: [ { "before": "する", "after": "して" } ] },
    "te-form negative": { forms: [ { "before": "する", "after": "しなくて" }, { "before": "する", "after": "しないで" } ] },
    "potential": { forms: [ { "before": "する", "after": "できる" } ] },
    "potential negative": { forms: [ { "before": "する", "after": "できない" } ] },
    "polite potential": { forms: [ { "before": "する", "after": "できます" } ] },
    "polite potential negative": { forms: [ { "before": "する", "after": "できません" } ] },
    "imperative": { forms: [ { "before": "する", "after": "しろ" } ] },
    "imperative negative": { forms: [ { "before": "する", "after": "するな" } ] },
    "passive": { forms: [ { "before": "する", "after": "される" } ] },
    "passive negative": { forms: [ { "before": "する", "after": "されない" } ] },
    "passive past": { forms: [ { "before": "する", "after": "された" } ] },
    "passive past negative": { forms: [ { "before": "する", "after": "されなかった" } ] },
    "passive te-form": { forms: [ { "before": "する", "after": "されて" } ] },
    "polite passive": { forms: [ { "before": "する", "after": "されます" } ] },
    "polite passive negative": { forms: [ { "before": "する", "after": "されません" } ] },
    "polite passive past": { forms: [ { "before": "する", "after": "されました" } ] },
    "polite passive past negative": { forms: [ { "before": "する", "after": "されませんでした" } ] },
    "causative": { forms: [ { "before": "する", "after": "させる" } ] },
    "causative negative": { forms: [ { "before": "する", "after": "させない" } ] },
    "causative past": { forms: [ { "before": "する", "after": "させた" } ] },
    "causative past negative": { forms: [ { "before": "する", "after": "させなかった" } ] },
    "causative passive": { forms: [ { "before": "する", "after": "させられる" } ] },
    "causative passive negative": { forms: [ { "before": "する", "after": "させられない" } ] },
    "causative passive past": { forms: [ { "before": "する", "after": "させられた" } ] },
    "causative passive past negative": { forms: [ { "before": "する", "after": "させられなかった" } ] },
    "progressive": { forms: [ { "before": "する", "after": "している" } ] },
    "progressive negative": { forms: [ { "before": "する", "after": "していない" } ] },
    "polite progressive": { forms: [ { "before": "する", "after": "しています" } ] },
    "polite progressive negative": { forms: [ { "before": "する", "after": "していません" } ] },
    "progressive past": { forms: [ { "before": "する", "after": "していた" } ] },
    "progressive past negative": { forms: [ { "before": "する", "after": "していなかった" } ] },
    "polite progressive past": { forms: [ { "before": "する", "after": "していました" } ] },
    "polite progressive past negative": { forms: [ { "before": "する", "after": "していませんでした" } ] },
    "desire": { forms: [ { "before": "する", "after": "したい" } ] },
    "desire negative": { forms: [ { "before": "する", "after": "したくない" } ] },
    "desire past": { forms: [ { "before": "する", "after": "したかった" } ] },
    "desire past negative": { forms: [ { "before": "する", "after": "したくなかった" } ] },
    "desire te-form": { forms: [ { "before": "する", "after": "したくて" } ] },
    "desire te-form negative": { forms: [ { "before": "する", "after": "したくなくて" } ] },
    "desire polite": { forms: [ { "before": "する", "after": "したいです" } ] },
    "desire polite negative": { forms: [ { "before": "する", "after": "したくないです" } ] },
    "desire polite past": { forms: [ { "before": "する", "after": "したかったです" } ] },
    "desire polite past negative": { forms: [ { "before": "する", "after": "したくなかったです" } ] },
    "volitional": { forms: [ { "before": "する", "after": "しよう" } ] },
    "polite volitional": { forms: [ { "before": "する", "after": "しましょう" } ] },
  },

  "i-adjective": {
    "negative": { forms: [ { "before": "い", "after": "くない" } ] },
    "polite": { forms: [ { "before": "い", "after": "いです" } ] },
    "polite negative": { forms: [ { "before": "い", "after": "くないです" }, { "before": "い", "after": "くありません" } ] },
    "past": { forms: [ { "before": "い", "after": "かった" } ] },
    "past negative": { forms: [ { "before": "い", "after": "くなかった" } ] },
    "polite past": { forms: [ { "before": "い", "after": "かったです" } ] },
    "polite past negative": { forms: [ { "before": "い", "after": "くなかったです" }, { "before": "い", "after": "くありませんでした" } ] },
    "te-form": { forms: [ { "before": "い", "after": "くて" } ] },
    "te-form negative": { forms: [ { "before": "い", "after": "くなくて" } ] },
  },

  "ii": {
    "negative": { forms: [ { "before": "いい", "after": "よくない" }, { "before": "よい", "after": "よくない" } ] },
    "polite": { forms: [ { "before": "いい", "after": "いいです" }, { "before": "よい", "after": "よいです" } ] },
    "polite negative": { forms: [ { "before": "いい", "after": "よくないです" }, { "before": "よい", "after": "よくないです" }, { "before": "いい", "after": "よくありません" }, { "before": "よい", "after": "よくありません" } ] },
    "past": { forms: [ { "before": "いい", "after": "よかった" }, { "before": "よい", "after": "よかった" } ] },
    "past negative": { forms: [ { "before": "いい", "after": "よくなかった" }, { "before": "よい", "after": "よくなかった" } ] },
    "polite past": { forms: [ { "before": "いい", "after": "よかったです" }, { "before": "よい", "after": "よかったです" } ] },
    "polite past negative": { forms: [ { "before": "いい", "after": "よくなかったです" }, { "before": "よい", "after": "よくなかったです" }, { "before": "いい", "after": "よくありませんでした" }, { "before": "よい", "after": "よくありませんでした" } ] },
    "te-form": { forms: [ { "before": "いい", "after": "よくて" }, { "before": "よい", "after": "よくて" } ] },
    "te-form negative": { forms: [ { "before": "いい", "after": "よくなくて" }, { "before": "よい", "after": "よくなくて" } ] },
  },

  "na-adjective": {
    "negative": { forms: [ { "before": "だ", "after": "じゃない" }, { "before": "だ", "after": "ではない" } ] },
    "polite": { forms: [ { "before": "だ", "after": "です" } ] },
    "polite negative": { forms: [ { "before": "だ", "after": "じゃないです" }, { "before": "だ", "after": "じゃありません" }, { "before": "だ", "after": "ではありません" } ] },
    "past": { forms: [ { "before": "だ", "after": "だった" } ] },
    "past negative": { forms: [ { "before": "だ", "after": "じゃなかった" }, { "before": "だ", "after": "でなかった" } ] },
    "polite past": { forms: [ { "before": "だ", "after": "でした" } ] },
    "polite past negative": { forms: [ { "before": "だ", "after": "じゃなかったです" }, { "before": "だ", "after": "じゃありませんでした" }, { "before": "だ", "after": "ではありませんでした" } ] },
    "te-form": { forms: [ { "before": "だ", "after": "で" } ] },
    "te-form negative": { forms: [ { "before": "だ", "after": "じゃなくて" }, { "before": "だ", "after": "でなくて" } ] },
  },
};